version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - run:
          name: Install dependencies
          command: apt update && apt-get -y install build-essential git sudo wget cmake libssl-dev libgmp-dev autoconf libtool
      - checkout
      - run: git submodule update --init --recursive
# TODO: Enable once there are unit/integration tests
#      - run: cmake -DDISABLE_DOCKER_BUILDS=ON . && make
#      - run: export GTEST_COLOR=1 && ctest -VV

  build_app:
    docker:
      - image: zondax/ledger-docker-bolos
    environment:
      - BOLOS_SDK=/root/project/deps/nanos-secure-sdk
      - BOLOS_ENV=/opt/bolos
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: make -C src/eos-app

  package_app:
    docker:
      - image: zondax/ledger-docker-bolos
    environment:
      - BOLOS_SDK=/root/project/deps/nanos-secure-sdk
      - BOLOS_ENV=/opt/bolos
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: make -C src/eos-app
      - run: make -C src/pkgapp
      - run: sudo apt-get -y install zip
      - run: zip -jr pkgapp.zip /root/project/pkgapp
      - store_artifacts:
          path: pkgapp.zip

workflows:
  version: 2
  build_all:
    jobs:
      - build
      - build_app
      - package_app:
          requires:
            - build
            - build_app
